# src/Zeega/EditorBundle/Resources/config/doctrine/Site.orm.yml
Zeega\DataBundle\Entity\Site:
    type: entity
    table: site
    manyToMany:
       users:
         targetEntity: Zeega\DataBundle\Entity\User
         mappedBy: sites
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
            nullable: true
        short:
            type: string
            length: 255
            nullable: true
            unique: true
        published:
            type: boolean
            nullable: true
        date_created:
            type: datetime
            nullable: true

 
 